language: python
python:
    - "2.6"
    - "2.7"

before_install:
    - apt-get update -qq
    - apt-get install -y libpcsclite-dev swig

install:
    - pip install wheel

script:
    - python setup.py bdist_wheel
