language: python
sudo: required

python:
    - "2.6"
    - "2.7"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libpcsclite-dev swig

install:
    - pip install wheel

script:
    - python setup.py bdist_wheel
