environment:

  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_compiler.cmd"
    SWIG: "C:\\swigwin-3.0.5"
    SWIG_VERSION: "3.0.5"
    SWIG_SHA256: "12b4e1905124f26f4f6970e23948238166aeb44001fa4ee5c1fd6bbbb7d981f4"

  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    #- PYTHON: "C:\\Python33"
    #  PYTHON_VERSION: "3.3.5"
    #  PYTHON_ARCH: "32"

    #- PYTHON: "C:\\Python34"
    #  PYTHON_VERSION: "3.4.1"
    #  PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"
      WINDOWS_SDK_VERSION: "v7.0"

    #- PYTHON: "C:\\Python33-x64"
    #  PYTHON_VERSION: "3.3.5"
    #  PYTHON_ARCH: "64"
    #  WINDOWS_SDK_VERSION: "v7.1"

    #- PYTHON: "C:\\Python34-x64"
    #  PYTHON_VERSION: "3.4.1"
    #  PYTHON_ARCH: "64"
    #  WINDOWS_SDK_VERSION: "v7.1"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "powershell appveyor\\install.ps1"

build: off

test_script:
  #- "%WITH_COMPILER% %PYTHON%/python setup.py test"
  - echo Skipped

after_test:
  - SET PATH=%SWIG%;%PATH%
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wheel"
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_wininst"
  - "%WITH_COMPILER% %PYTHON%/python setup.py bdist_msi"

artifacts:
  - path: dist\*

#on_success:
#  - TODO: upload the content of dist/*.whl to a public wheelhouse
